#!/bin/sh

### BEGIN INIT INFO
# Provides:      duplex
# Default-Start: 5
# Default-Stop:
# Required-Start: vsftpd
# Required-Stop:
### END INIT INFO

case "$1" in
	start)
		sudo -uscan ~scan/script &
		;;
	stop)
		sudo -uscan killall script
		;;
	restart)
		"$0" stop && "$0" start
		;;
	*)
		echo "Unsupported!" >&2
		exit 1
esac

true
